# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
    push:
        tags: '*'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Set env
                run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
            -   uses: actions/checkout@v3
            -   name: Use Node.js 18.x
                uses: actions/setup-node@v3
                with:
                    node-version: 18.x
                    cache: 'npm'
            -   run: npm ci
            -   run: npm install -g gh
            -   run: npm run build --if-present
            -   run: gh release upload ${{env.RELEASE_VERSION}} main.js manifest.json
                env:
                    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
